api_hash: d2f6086d54bf32d27b90e124fd0f52d5
api_id: 23924677
bot_token: 8309693752:AAG75kcrrPdoo9a5-mHE12mTzX2xJ3aKESg

file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
max_download_task: 2
save_path: /Volumes/My Book/Downloads/telegram
language: ZH
